// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: collector/pkg/grpc_contracts/v1/collector.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Details []*anypb.Any `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *ErrorStatus) Reset() {
	*x = ErrorStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatus) ProtoMessage() {}

func (x *ErrorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatus.ProtoReflect.Descriptor instead.
func (*ErrorStatus) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorStatus) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{1}
}

type RegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*RegisterResp_Resp
	//	*RegisterResp_Error
	Response isRegisterResp_Response `protobuf_oneof:"response"`
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{2}
}

func (m *RegisterResp) GetResponse() isRegisterResp_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *RegisterResp) GetResp() *SuccessRegisterResp {
	if x, ok := x.GetResponse().(*RegisterResp_Resp); ok {
		return x.Resp
	}
	return nil
}

func (x *RegisterResp) GetError() *ErrorStatus {
	if x, ok := x.GetResponse().(*RegisterResp_Error); ok {
		return x.Error
	}
	return nil
}

type isRegisterResp_Response interface {
	isRegisterResp_Response()
}

type RegisterResp_Resp struct {
	Resp *SuccessRegisterResp `protobuf:"bytes,1,opt,name=resp,proto3,oneof"`
}

type RegisterResp_Error struct {
	Error *ErrorStatus `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RegisterResp_Resp) isRegisterResp_Response() {}

func (*RegisterResp_Error) isRegisterResp_Response() {}

type SuccessRegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId       int64                  `protobuf:"varint,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AuthExpiredDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=authExpiredDate,proto3" json:"authExpiredDate,omitempty"`
}

func (x *SuccessRegisterResp) Reset() {
	*x = SuccessRegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessRegisterResp) ProtoMessage() {}

func (x *SuccessRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessRegisterResp.ProtoReflect.Descriptor instead.
func (*SuccessRegisterResp) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{3}
}

func (x *SuccessRegisterResp) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *SuccessRegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SuccessRegisterResp) GetAuthExpiredDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthExpiredDate
	}
	return nil
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId int64 `protobuf:"varint,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenReq) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*RefreshTokenResp_Resp
	//	*RefreshTokenResp_Error
	Response isRefreshTokenResp_Response `protobuf_oneof:"response"`
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{5}
}

func (m *RefreshTokenResp) GetResponse() isRefreshTokenResp_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *RefreshTokenResp) GetResp() *RefreshTokenSuccessResp {
	if x, ok := x.GetResponse().(*RefreshTokenResp_Resp); ok {
		return x.Resp
	}
	return nil
}

func (x *RefreshTokenResp) GetError() *ErrorStatus {
	if x, ok := x.GetResponse().(*RefreshTokenResp_Error); ok {
		return x.Error
	}
	return nil
}

type isRefreshTokenResp_Response interface {
	isRefreshTokenResp_Response()
}

type RefreshTokenResp_Resp struct {
	Resp *RefreshTokenSuccessResp `protobuf:"bytes,1,opt,name=resp,proto3,oneof"`
}

type RefreshTokenResp_Error struct {
	Error *ErrorStatus `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RefreshTokenResp_Resp) isRefreshTokenResp_Response() {}

func (*RefreshTokenResp_Error) isRefreshTokenResp_Response() {}

type RefreshTokenSuccessResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId       int64                  `protobuf:"varint,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AuthExpiredDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=authExpiredDate,proto3" json:"authExpiredDate,omitempty"`
}

func (x *RefreshTokenSuccessResp) Reset() {
	*x = RefreshTokenSuccessResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshTokenSuccessResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenSuccessResp) ProtoMessage() {}

func (x *RefreshTokenSuccessResp) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenSuccessResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenSuccessResp) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenSuccessResp) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *RefreshTokenSuccessResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenSuccessResp) GetAuthExpiredDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthExpiredDate
	}
	return nil
}

type SendMetricsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendMetricsReq) Reset() {
	*x = SendMetricsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMetricsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMetricsReq) ProtoMessage() {}

func (x *SendMetricsReq) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMetricsReq.ProtoReflect.Descriptor instead.
func (*SendMetricsReq) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{7}
}

type SendMetricsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendMetricsResp) Reset() {
	*x = SendMetricsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMetricsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMetricsResp) ProtoMessage() {}

func (x *SendMetricsResp) ProtoReflect() protoreflect.Message {
	mi := &file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMetricsResp.ProtoReflect.Descriptor instead.
func (*SendMetricsResp) Descriptor() ([]byte, []int) {
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP(), []int{8}
}

var File_collector_pkg_grpc_contracts_v1_collector_proto protoreflect.FileDescriptor

var file_collector_pkg_grpc_contracts_v1_collector_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x0b, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x22, 0xa4, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x13, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x44, 0x0a, 0x0f, 0x61, 0x75, 0x74, 0x68, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x61, 0x75, 0x74, 0x68,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x2f, 0x0a, 0x0f, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0xac, 0x01, 0x0a,
	0x10, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x4a, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x34, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x17,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x44, 0x0a, 0x0f, 0x61,
	0x75, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0f, 0x61, 0x75, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x32, 0xd0, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x68, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x29, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x6d,
	0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x2d, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x6a, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x2b, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescOnce sync.Once
	file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescData = file_collector_pkg_grpc_contracts_v1_collector_proto_rawDesc
)

func file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescGZIP() []byte {
	file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescOnce.Do(func() {
		file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescData = protoimpl.X.CompressGZIP(file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescData)
	})
	return file_collector_pkg_grpc_contracts_v1_collector_proto_rawDescData
}

var file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_collector_pkg_grpc_contracts_v1_collector_proto_goTypes = []interface{}{
	(*ErrorStatus)(nil),             // 0: collector.grpc_contracts.v1.ErrorStatus
	(*RegisterReq)(nil),             // 1: collector.grpc_contracts.v1.RegisterReq
	(*RegisterResp)(nil),            // 2: collector.grpc_contracts.v1.RegisterResp
	(*SuccessRegisterResp)(nil),     // 3: collector.grpc_contracts.v1.SuccessRegisterResp
	(*RefreshTokenReq)(nil),         // 4: collector.grpc_contracts.v1.RefreshTokenReq
	(*RefreshTokenResp)(nil),        // 5: collector.grpc_contracts.v1.RefreshTokenResp
	(*RefreshTokenSuccessResp)(nil), // 6: collector.grpc_contracts.v1.RefreshTokenSuccessResp
	(*SendMetricsReq)(nil),          // 7: collector.grpc_contracts.v1.SendMetricsReq
	(*SendMetricsResp)(nil),         // 8: collector.grpc_contracts.v1.SendMetricsResp
	(*anypb.Any)(nil),               // 9: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_collector_pkg_grpc_contracts_v1_collector_proto_depIdxs = []int32{
	9,  // 0: collector.grpc_contracts.v1.ErrorStatus.details:type_name -> google.protobuf.Any
	3,  // 1: collector.grpc_contracts.v1.RegisterResp.resp:type_name -> collector.grpc_contracts.v1.SuccessRegisterResp
	0,  // 2: collector.grpc_contracts.v1.RegisterResp.error:type_name -> collector.grpc_contracts.v1.ErrorStatus
	10, // 3: collector.grpc_contracts.v1.SuccessRegisterResp.authExpiredDate:type_name -> google.protobuf.Timestamp
	6,  // 4: collector.grpc_contracts.v1.RefreshTokenResp.resp:type_name -> collector.grpc_contracts.v1.RefreshTokenSuccessResp
	0,  // 5: collector.grpc_contracts.v1.RefreshTokenResp.error:type_name -> collector.grpc_contracts.v1.ErrorStatus
	10, // 6: collector.grpc_contracts.v1.RefreshTokenSuccessResp.authExpiredDate:type_name -> google.protobuf.Timestamp
	1,  // 7: collector.grpc_contracts.v1.Collector.RegisterService:input_type -> collector.grpc_contracts.v1.RegisterReq
	4,  // 8: collector.grpc_contracts.v1.Collector.RefreshToken:input_type -> collector.grpc_contracts.v1.RefreshTokenReq
	7,  // 9: collector.grpc_contracts.v1.Collector.SendMetrics:input_type -> collector.grpc_contracts.v1.SendMetricsReq
	2,  // 10: collector.grpc_contracts.v1.Collector.RegisterService:output_type -> collector.grpc_contracts.v1.RegisterResp
	5,  // 11: collector.grpc_contracts.v1.Collector.RefreshToken:output_type -> collector.grpc_contracts.v1.RefreshTokenResp
	8,  // 12: collector.grpc_contracts.v1.Collector.SendMetrics:output_type -> collector.grpc_contracts.v1.SendMetricsResp
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_collector_pkg_grpc_contracts_v1_collector_proto_init() }
func file_collector_pkg_grpc_contracts_v1_collector_proto_init() {
	if File_collector_pkg_grpc_contracts_v1_collector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessRegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshTokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshTokenSuccessResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMetricsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMetricsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*RegisterResp_Resp)(nil),
		(*RegisterResp_Error)(nil),
	}
	file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*RefreshTokenResp_Resp)(nil),
		(*RefreshTokenResp_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collector_pkg_grpc_contracts_v1_collector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_pkg_grpc_contracts_v1_collector_proto_goTypes,
		DependencyIndexes: file_collector_pkg_grpc_contracts_v1_collector_proto_depIdxs,
		MessageInfos:      file_collector_pkg_grpc_contracts_v1_collector_proto_msgTypes,
	}.Build()
	File_collector_pkg_grpc_contracts_v1_collector_proto = out.File
	file_collector_pkg_grpc_contracts_v1_collector_proto_rawDesc = nil
	file_collector_pkg_grpc_contracts_v1_collector_proto_goTypes = nil
	file_collector_pkg_grpc_contracts_v1_collector_proto_depIdxs = nil
}
